name: Deploy to ECR

on: 
  push:
    branches: [ master ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: assignment-1
        IMAGE_TAG: v0.1
      run: |
        git clone https://github.com/119917227-mysenca/clo835-assignment-1.git
        cd clo835-assignment-1
        # Docker build
        docker build -t my_db -f Dockerfile_mysql . 
        docker build -t my_app -f Dockerfile .
        # Unit test
        docker run -d -e MYSQL_ROOT_PASSWORD=pw  my_db
        echo "Pause for 10 seconds to let container start"
        sleep 10
        export DBHOST=172.17.0.2
        export DBPORT=3306
        export DBUSER=root
        export DATABASE=employees
        export DBPWD=pw
        export APP_COLOR=blue
        # Unit test
        docker run -p 8080:8080  -e DBHOST=$DBHOST -e DBPORT=$DBPORT -e  DBUSER=$DBUSER -e DBPWD=$DBPWD  my_app
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        curl localhost:8080
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
